/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AAvalieComandos extends PComandos
{
    private PExp _exp_;
    private PCasoComando _casoComando_;
    private PSenaoComandoDoispontos _senaoComandoDoispontos_;

    public AAvalieComandos()
    {
        // Constructor
    }

    public AAvalieComandos(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PCasoComando _casoComando_,
        @SuppressWarnings("hiding") PSenaoComandoDoispontos _senaoComandoDoispontos_)
    {
        // Constructor
        setExp(_exp_);

        setCasoComando(_casoComando_);

        setSenaoComandoDoispontos(_senaoComandoDoispontos_);

    }

    @Override
    public Object clone()
    {
        return new AAvalieComandos(
            cloneNode(this._exp_),
            cloneNode(this._casoComando_),
            cloneNode(this._senaoComandoDoispontos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvalieComandos(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PCasoComando getCasoComando()
    {
        return this._casoComando_;
    }

    public void setCasoComando(PCasoComando node)
    {
        if(this._casoComando_ != null)
        {
            this._casoComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoComando_ = node;
    }

    public PSenaoComandoDoispontos getSenaoComandoDoispontos()
    {
        return this._senaoComandoDoispontos_;
    }

    public void setSenaoComandoDoispontos(PSenaoComandoDoispontos node)
    {
        if(this._senaoComandoDoispontos_ != null)
        {
            this._senaoComandoDoispontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoComandoDoispontos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._casoComando_)
            + toString(this._senaoComandoDoispontos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._casoComando_ == child)
        {
            this._casoComando_ = null;
            return;
        }

        if(this._senaoComandoDoispontos_ == child)
        {
            this._senaoComandoDoispontos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._casoComando_ == oldChild)
        {
            setCasoComando((PCasoComando) newChild);
            return;
        }

        if(this._senaoComandoDoispontos_ == oldChild)
        {
            setSenaoComandoDoispontos((PSenaoComandoDoispontos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
