/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import java.util.*;
import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class AEnquantoComandos extends PComandos
{
    private PExpLogica _expLogica_;
    private final LinkedList<PComandos> _a_ = new LinkedList<PComandos>();
    private PComandos _b_;

    public AEnquantoComandos()
    {
        // Constructor
    }

    public AEnquantoComandos(
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") List<?> _a_,
        @SuppressWarnings("hiding") PComandos _b_)
    {
        // Constructor
        setExpLogica(_expLogica_);

        setA(_a_);

        setB(_b_);

    }

    @Override
    public Object clone()
    {
        return new AEnquantoComandos(
            cloneNode(this._expLogica_),
            cloneList(this._a_),
            cloneNode(this._b_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnquantoComandos(this);
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public LinkedList<PComandos> getA()
    {
        return this._a_;
    }

    public void setA(List<?> list)
    {
        for(PComandos e : this._a_)
        {
            e.parent(null);
        }
        this._a_.clear();

        for(Object obj_e : list)
        {
            PComandos e = (PComandos) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._a_.add(e);
        }
    }

    public PComandos getB()
    {
        return this._b_;
    }

    public void setB(PComandos node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_)
            + toString(this._a_)
            + toString(this._b_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._a_.remove(child))
        {
            return;
        }

        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        for(ListIterator<PComandos> i = this._a_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandos) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._b_ == oldChild)
        {
            setB((PComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
