/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladores.node;

import java.util.*;
import compiladores.analysis.*;

@SuppressWarnings("nls")
public final class ALeiaComandos extends PComandos
{
    private final LinkedList<PVar> _vars_ = new LinkedList<PVar>();
    private PVar _var_;

    public ALeiaComandos()
    {
        // Constructor
    }

    public ALeiaComandos(
        @SuppressWarnings("hiding") List<?> _vars_,
        @SuppressWarnings("hiding") PVar _var_)
    {
        // Constructor
        setVars(_vars_);

        setVar(_var_);

    }

    @Override
    public Object clone()
    {
        return new ALeiaComandos(
            cloneList(this._vars_),
            cloneNode(this._var_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeiaComandos(this);
    }

    public LinkedList<PVar> getVars()
    {
        return this._vars_;
    }

    public void setVars(List<?> list)
    {
        for(PVar e : this._vars_)
        {
            e.parent(null);
        }
        this._vars_.clear();

        for(Object obj_e : list)
        {
            PVar e = (PVar) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._vars_.add(e);
        }
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vars_)
            + toString(this._var_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vars_.remove(child))
        {
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PVar> i = this._vars_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVar) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
